#!/usr/bin/env bash

. /usr/share/sbt/sbt-launch-lib.bash

propsfile="/etc/giter8/giter8.properties"

usage() {
  # Just call underlying g8 for usage info.
  runAlternateBoot $propsfile
}

runAlternateBoot $propsfile $@
